### PR TITLE
Add processor to reset styleCache. Fixes #26.

### LINKED ISSUE #26: Whitespace not removed in some case instances
Just trying this for the first time. Config is via PostCSS plugin inside a gulp task. No options set and I get weird whitespace included in lots of cases. Here is a tiny snippet:

```
background-repeat:no-repeat}.sport_1:before,.sport_31:before,.sport_74:before,.sport_82:before{
	background-position:50% 2px}.sport_2:before,.sport_73:before,.sport_81:before{
	background-position:50% -1081px}.sport_3:before{
	background-position:50% -2109px}.sport_4:before,.sport_85:before{
	background-position:50% -3135px}.sport_5:before,.sport_129:before,.sport_130:before,.sport_131:before,.sport_132:before,.sport_133:before,.sport_134:before,.sport_135:before,.sport_136:before,.sport_137:before,.sport_800:before,.sport_996:before{
	background-position:50% -57px}.sport_6:before{
	background-position:50% -855pt}.sport_7:before{
	background-position:50% -2166px}.sport_8:before{
	background-position:50% -2337px}.sport_9:before{
```

Expected:

```
background-repeat:no-repeat}.sport_1:before,.sport_31:before,.sport_74:before,.sport_82:before{background-position:50% 2px}.sport_2:before,.sport_73:before,.sport_81:before{background-position:50% -1081px}.sport_3:before{background-position:50% -2109px}.sport_4:before,.sport_85:before{background-position:50% -3135px}.sport_5:before,.sport_129:before,.sport_130:before,.sport_131:before,.sport_132:before,.sport_133:before,.sport_134:before,.sport_135:before,.sport_136:before,.sport_137:before,.sport_800:before,.sport_996:before{background-position:50% -57px}.sport_6:before{background-position:50% -855pt}.sport_7:before{background-position:50% -2166px}.sport_8:before{background-position:50% -2337px}.sport_9:before{
```

### PR DESCRIPTION
**Pull request by ben-eb**
This should fix any whitespace issues when combining cssnano with PostCSS plugins that utilise `node.clone()`. Would be nice to get some confirmation.

/cc @meuwka @faergeek @benfrain @ai

### CODE REVIEW

**Comment by ben-eb** [comment]
Apparently it's failing my existing tests. Will investigate. :smile:

**Comment by faergeek** [comment]
I'm not sure, but may be it can help here https://github.com/morishitter/cssfmt

**Comment by ben-eb** [comment]
For formatters, they would probably need to define their own format object, rather than resetting all of them to empty strings.

**Comment by ai** [comment]
Looks like temporary solution, but if it will clean code in few projects, why not.

**Pull request merged**
