### PR TITLE
Tidy up

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by TrySound** [comment]
@ben-eb I do not use `0 0` value

**Comment by TrySound** [comment]
@ben-eb I just replaced `none` with `0`

**Comment by TrySound** [comment]
@ben-eb In future we need to move it to merge-longhand maybe

**Comment by ben-eb** [comment]
Yeah, none to 0 is what I was talking about. :smile: 

https://github.com/jakubpawlowicz/clean-css/issues/226

**Comment by TrySound** [comment]
@ben-eb But why you do the same with outline?

**Comment by ben-eb** [comment]
Thanks! :+1:

**Pull request merged**
