### PR TITLE
Add safe option

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by ScottSmith95** [comment]
I'd love to see this. Perfect for implementing in a large project.

**Comment by TrySound** [comment]
@ScottSmith95 Will be improved with time.

**Comment by ben-eb** [comment]
Should also look at disabling unused rule removal for this, too.

**Comment by ben-eb** [comment]
I'll have a look at updating the tests tomorrow. :smile:

**Comment by MentalGear** [comment]
Could someone give an example on how to use this option with gulp?

**Comment by TrySound** [comment]
@MentalGear 
```js
var postcss = require('gulp-postcss');
var cssnano = require('cssnano');

/* ... */

.pipe(postcss([
  cssnano({
    safe: true
  })
]))
```

**Comment by MentalGear** [comment]
Thx, figured it out :P

**Pull request merged**
